// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_InvoiceManagement.cpp"
#include "EWIEGA46WW/moc_managerproduct.cpp"
#include "EWIEGA46WW/moc_minisupermarketmanagement.cpp"
#include "EWIEGA46WW/moc_my_customer.cpp"
